version: '3.2'

volumes:
  buber_mongo_volume:

services:
  buber_web:
    image: openjdk:8-jdk-alpine
    ports:
      - 8080:8080
    container_name: buber_backend
    depends_on:
      - buber_mongo
    volumes:
      - type: bind
        source: ./build
        target: /opt/buber/build
    command: java -jar /opt/buber/build/buber-fat-0.0.1.jar --spring.profiles.active=stg

  buber_mongo:
    image: mongo
    container_name: buber_mongo
    volumes:
      - type: volume
        source: buber_mongo_volume
        target: /data/db
