version: '3.2'

volumes:
  buber_mongo_volume:
  buber_ads_volume:

services:
  buber_web:
    image: openjdk:8-jdk-alpine
    expose:
      - 8080
    ports:
      - 8888:8080
    container_name: buber_backend
    depends_on:
      - buber_mongo
    volumes:
      - type: bind
        source: ./build
        target: /buber
      - type: volume
        source: buber_ads_volume
        target: /root/.buber
    command: java -jar /buber/libs/buber-0.0.1.jar --spring.profiles.active=stg

  buber_mongo:
    image: mongo
    container_name: buber_mongo
    volumes:
      - type: volume
        source: buber_mongo_volume
        target: /data/db
    expose:
      - 27017
    ports:
      - 27018:27017
